[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2", "conan", "mypy>=0.900"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
root = ".."
write_to = "pytket/pytket/_version.py"
write_to_template = '__version__ = "{version}"'
